# docker mysql
spring:
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/flo
#      username: hayun
#      password: password
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true

# h2 database
#spring.datasource.url=jdbc:h2:file:./data/demo
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=password

# jpa option
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace